server:
  port: 8080
keycloak:
  individuals:
    base-url: http://localhost:7080
    realm: fintech-app
    client-id: individuals
    client-secret: QF8rGFdWsF6xzdgvjrEnVhVAHGlpFqLl # set new value from Keycloak
spring:
  profiles:
    active: dev
  application:
    name: fin-tech-app
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${keycloak.individuals.base-url}/realms/${keycloak.individuals.realm}
        registration:
          keycloak-admin-client-registration:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: ${keycloak.individuals.client-id}
            client-secret: ${keycloak.individuals.client-secret}
      resourceserver:
        jwt:
          issuer-uri: ${spring.security.oauth2.client.provider.keycloak.issuer-uri}