keycloak:
  server:
    base-url: http://localhost:7080/
  admin:
    realm: master
    client-id: admin-cli
    username: keycloak
    password: keycloak
    grant-type: password
  fintech:
    realm: fintech-app
    client-id: individuals-api

server:
  port: 8080
spring:
  application:
    name: fin-tech-app
  security:
