name: keycloak

services:
  postgres:
    image: postgres:17
    container_name: postgres-kc
    environment:
      POSTGRES_USER: ${KC_PG_USER_PASS}
      POSTGRES_PASSWORD: ${KC_PG_USER_PASS}
      POSTGRES_DB: ${KC_PG_DB}
    networks:
      - keycloak_network
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: keycloak
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_PG_USER_PASS}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_PG_USER_PASS}
      KC_DB: postgres
      KC_DB_USERNAME: ${KC_PG_USER_PASS}
      KC_DB_PASSWORD: ${KC_PG_USER_PASS}
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: ${KC_PG_DB}
    command: [ "start-dev", "--import-realm" ]
    volumes:
      - ./realm-config.json:/opt/keycloak/data/import/realm-config.json
    ports:
      - "7080:8080"
    depends_on:
      - postgres
    networks:
      - keycloak_network
#  pgadmin:
#    image: dpage/pgadmin4:9.4.0
#    container_name: pgadmin
#    environment:
#      PGADMIN_DEFAULT_EMAIL: keycloak@keycloak.com
#      PGADMIN_DEFAULT_PASSWORD: keycloak
#    ports:
#      - 8888:80
#    networks:
#      - keycloak_network
volumes:
  local_pgdata:
networks:
  keycloak_network:
    driver: bridge